lib/geocoder/agolgeocoder.js, test/geocoder/agolgeocoder.js
As per [this spec](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-service-output.htm#ESRI_SECTION1_42D7D3D0231241E9B656C01438209440) street address number is referenced by key `AddNum` and not `AddrNum`. The test has been updated accordingly
This PR fixes #69
=> Referencing Street Address Number correctly for ArcGIS provider

lib/geocoder/agolgeocoder.js, test/geocoder/agolgeocoder.js
The ArcGIS provider was flip flopping the lat and lng for geocode requests. Specs have been updated
=> Latitude and Longitude were flip flopped for ArcGIS provider

lib/geocoder.js
it already has the value 'raw', it's just unprotected and enumerable...
=> Simplified defineProperty(data,'raw') statement

CHANGELOG.md, README.md, bin/geocoder-reverse, lib/geocoder.js, lib/geocoder/abstractgeocoder.js, lib/geocoder/agolgeocoder.js, lib/geocoder/googlegeocoder.js, lib/geocoder/mapquestgeocoder.js, lib/geocoder/opencagegeocoder.js, lib/geocoder/openmapquestgeocoder.js, lib/geocoder/openstreetmapgeocoder.js, lib/httpadapter/httpadapter.js, test/geocoder/agolgeocoder.js, test/geocoder/googlegeocoder.js, test/geocoder/mapquestgeocoder.js, test/geocoder/nominatimmapquestgeocoder.js, test/geocoder/opencagegeocoder.js, test/geocoder/openmapquestgeocoder.js, test/geocoder/openstreetmapgeocoder.js
Made first argument of `geocoder.reverse` a query-object {lat,lon}, so further parameters can be supported by geocoders, (See PR #86), and the API is analogue to `geocode(value, callback)`.
Old (lat, long, callback)-API is still supported, so it's fully backward compatible.
Based on fixes from PR #83 and #84
=> Change reverse api

lib/geocoder/freegeoipgeocoder.js, test/geocoder/freegeoipgeocoder.js
It appears freegeoip's format for their response JSON has changed. It now uses zip_code. See this example:
https://freegeoip.net/json/github.com
=> updating freegeoip zipcode response format

lib/httpadapter/httpadapter.js
The reverse function of openstreetmap and nominatimmapquest doesn't accept nodejs/iojs default http user-agent anymore.
I added a custom user-agent (firefox 31.0 on linux) to prevent the issue.
=> Fix nominatimmapquest and openstreetmap reverse function

lib/geocoder/geocodio.js, lib/geocoder/geocodiogeocoder.js, lib/geocoder/googlegeocoder.js, lib/geocoder/opencagegeocoder.js, lib/geocoder/openmapquestgeocoder.js, lib/geocoderfactory.js, test/geocoder/geocodiogeocoder.js, test/geocoder/googlegeocoder.js, test/geocoder/opencagegeocoder.js
Just because I get a result doesn't mean it's right. For example, I may try to geocode a house address & only get the lat lng of a city. Ideally, if a service isn't accurate enough, I could retry it with another service (that's why your package is great).
That's what `confidence` is for. Within the extras object (for google, openmapquest, opencage, and geocodio) there's a confidence score from 0 to 1 (This is subjectively normalized based on my experience with each, although I tried to document as much as I could). A 1 means rooftop, .9 means interpolated, .8 means street, .7 means neighborhood-ish, etc. I've never used the other services, but could add confidence to those as well if desired.
Additionally, I added a module for geocod.io, which is a great source for TIGER data in the US.
=> Add confidence to geocodes & added geocodio module

lib/httpadapter/httpadapter.js
When content-type were not present in http header an uncaught exception
were thrown.
This fixes https://github.com/nchaulet/node-geocoder/issues/107
=> handled an error with http response.

lib/geocoder/googlegeocoder.js, test/geocoder/googlegeocoder.js
The google api can try and be clever and return partial "fuzzy" matches.
In a project I am currently working on we didn't require these.  I was able to filter them out by checking the results.raw.results object.  
I thought it may be useful to add 'excludePartialMatches' option to allow these to be filtered out.
=> GoogleGeocode - Exclude partial matches

README.md, lib/geocoder/nominatimmapquestgeocoder.js, lib/geocoder/openstreetmapgeocoder.js, lib/geocoderfactory.js, test/geocoder/nominatimmapquestgeocoder.js
All Nominatim and Xapi requests require a key starting September 15, 2015.
=> Added required api Key to Nominatimmapquestgeocoder

README.md, lib/geocoder/teleportgeocoder.js, lib/geocoderfactory.js, test/geocoder/teleportgeocoder.js
I implemented support for forward and reverse city geocoding using Teleport APIs.
Teleport geocoding APIs are based on GeoNames cities1000 (i.e. cities with population > 1000) dataset, but with different logic for searching for cities by name, administrative division and country.
Disclaimer: I work for @teleport
Let me know if there's anything that needs to be changed in order to merge.
=> Add Teleport geocoder

test/geocoder/yandexgeocoder.js
Seems this was left over from copying from OpenCageGeocoder.
=> Fix YandexGeocoder test name

lib/error/httperror.js, lib/geocoderfactory.js, lib/httpadapter/httpadapter.js, test/geocoderfactory.js, test/httpadapter/httpadapter.js
Built in node timeout can be too long. Helpful to be able to override at client level.
* adds `timeout` option to `HttpAdapter`
* will throw `HttpError` which mimics nodes built in timeout error
* to test, will need to kill your network connection (otherwise will silently succeed)
=> adds http(s) request timeout support

README.md, lib/geocoder/opendatafrancegeocoder.js, lib/geocoderfactory.js, test/geocoder/opendatafrancegeocoder.js
I implemented support for forward and reverse city geocoding using opendata from french government portal.
Full documentation of this API is here : https://adresse.data.gouv.fr/api/
Unit testing included
Let me know if there's anything that needs to be changed in order to merge.
We will use this module with this geocoder soon in one of our project ;)
=> Add Opendata France geocoder

lib/geocoder/googlegeocoder.js, test/geocoder/googlegeocoder.js
Addresses issue #166 which I created. This assumes address components are always going to be returned from most specific to least specific.
=> Google: Neighborhood now resolves to most specific property

lib/geocoder/googlegeocoder.js
Buffer.toString('binary') in Node.js 6 (v6.2.1) results with different string compared to Node.js 4 (v4.2.2).
Example:
```
const str = '9!H+88WK#1Hf1GR!9acS@E/8d+A1bM';
const hmacBinary = crypto.createHmac('sha1', new Buffer(str, 'base64').toString('binary'));
hmacBinary.update('some data to hash');
// node 4: A+7vPWdMrDCw1M6xvytfodqdwzg=
// node 6: kOGH7NoCHjJafi6rANRTfrH19z0=
console.log(hmacBinary.digest('base64'));
const hmac = crypto.createHmac('sha1', new Buffer(str, 'base64'));
hmac.update('some data to hash');
// node 4: A+7vPWdMrDCw1M6xvytfodqdwzg=
// node 6: A+7vPWdMrDCw1M6xvytfodqdwzg=
console.log(hmac.digest('base64'));
```
As you can see above, resulting string is different on Node.js 4 and 6, which causes Google API to respond with 403 on Node.js 6, because key is encrypted …
=> Google Geocoding: pass buffer to crypto.createHmac instead of string

README.md, lib/geocoder/locationiqgeocoder.js, lib/geocoderfactory.js, test/geocoder/locationiqgeocoder.js, test/geocoderfactory.js
Adds an other provider which connects to [locationiq](http://locationiq.org/) where openstreetmap data is made available as "blazing fast geocoding" and just an api key is required to authentificate.
Tests included.
Relates to #178
=> feat: adds locationiq geocoder

lib/geocoder.js
In the process of mapping provider names to results in 2b189b9, it looks like the `raw` attribute of the `data` object is lost.
This pull request simply captures the `raw` attribute and re-sets it (with the intended property configuration) after the mapping process.
There may well be a more elegant way to do this, but I’m hoping this is a simple fix.
=> Fix: `raw` attribute gone missing from results

lib/geocoder/googlegeocoder.js
Google often pushes "locality" as as the non-zero element of the "types" array when a city name has colloquial usage (in addition to its other uses, such as a locality). This was causing the library not to find the city amongst the Google results for several major cities such as Sydney, Australia, which Google returns as:
"address_components" : [
{
"long_name" : "Sydney",
"short_name" : "Sydney",
"types" : [ "colloquial_area", "locality", "political" ]
},
{
"long_name" : "New South Wales",
"short_name" : "NSW",
"types" : [ "administrative_area_level_1", "political" ]
},
{
"long_name" : "Australia",
"short_name" : "AU",
"types" : [ "country", "political" ]
}
]
This pull request simply has the library look at all the different types of each address component when searching for the …
=> Added support for multiple types of a single google address component 

lib/geocoder/yandexgeocoder.js
Latitude and longitude are reversed for Yandex geocoder.
Check this — `Moscow, Russia` query rusults:
For Yandex:
```
latitude:"37.617635"
longitude:"55.755814"
city:"Москва"
state:"Москва"
streetName:null
streetNumber:null
countryCode:"RU"
country:"Россия"
provider:"yandex"
```
For OpenStreetMap:
```
latitude:55.7507178
longitude:37.6176606
country:"РФ"
city:"Москва"
state:"Москва"
countryCode:"RU"
provider:"openstreetmap"
```
For Google:
```
formattedAddress:"Moscow, Russia"
latitude:55.755826
longitude:37.6172999
city:"Moscow"
country:"Russia"
countryCode:"RU"
provider:"google"
```
=> Yandex — Latitude and longitude are reversed

lib/geocoder/yandexgeocoder.js, test/geocoder/yandexgeocoder.js
The latitude and longitude from Yandex geocoding result are string,
while I expected to get float numbers (like google geocoding result).
=> Yandex: return float lat/lng instead of string

lib/geocoder/abstractgeocoder.js
If use object for request in geocode method get error:
```
TypeError: Cannot convert object to primitive value
at GoogleGeocoder.AbstractGeocoder.geocode (/home/enniel/Code/api-server/node_modules/node-geocoder/lib/geocoder/abstractgeocoder.js:64:11)
at Proxy.<anonymous> (/home/enniel/Code/api-server/node_modules/node-geocoder/lib/geocoder.js:25:24)
```
This code don`t workded:
```
const Geocoder = geocoder(config)
Geocoder.geocode({ address: '29 Av. des Champs-Élysées, 75008 Paris, France' })
```
This code worked:
```
const Geocoder = geocoder(config)
Geocoder.geocode('29 Av. des Champs-Élysées, 75008 Paris, France')
```
=> fix bug with object address

lib/geocoder/mapquestgeocoder.js
- See it live: https://developer.mapquest.com/documentation/samples/geocoding/v1/address/
=> Add SSL to API endpoint (mapquestapi.com)

lib/geocoder/geocodiogeocoder.js
- See the documentation: https://geocod.io/docs/
- Live in-browser test: https://api.geocod.io/v1/geocode?q=1109+N+Highland+St%2c+Arlington+VA&api_key=API_KEY
=> Add SSL to API endpoint (api.geocod.io)

lib/geocoder/freegeoipgeocoder.js
- See it live: https://freegeoip.net/json/
- Remark: FreeGeoIP will be deprecated as of July 1st, 2018. For more information, see: 
https://github.com/apilayer/freegeoip#readme
=> Add SSL to API endpoint (freegeoip.net)

lib/geocoder/locationiqgeocoder.js
Analogous to the [OSM geocoder code](https://github.com/nchaulet/node-geocoder/blob/master/lib/geocoder/openstreetmapgeocoder.js#L71-L74) I changed the code of the LocationIQ Geocoder to only uppercase the country code of the address, if one exists.
=> LocationIQ: Only uppercase the country code if it is set

README.md, lib/geocoder/tomtomgeocoder.js
Pull request will update the TomTom geocoder API url and handle the new API response.
Related to ticket: #272 
Please review the code (it does work for my use) but I was not sure why countrycode returned an countryISO3 before. Although it is available on the new API, I assume a normal countrycode is prefered. Also added a hardcoded limit but not sure how this is for the other geocoder libs. The rest should be ok.
=> Updated tomtom geocoder API

lib/geocoderfactory.js
Addendum to #279 
Completely missed this the first time around. When I updated the tests, I believe I was accessing the HereGeocoder constructor directly, thus obscuring this bug.
Sorry that I didn't catch this before a release was pushed. 
---
Perhaps simply passing in `extra` to the second constructor argument would prevent this mistake in the future?
=> Make sure to assign `production` option in the HERE geocoder constructor

lib/geocoder/yandexgeocoder.js, lib/geocoderfactory.js
The current release doesn't add apiKey to yandex request and return 403 Forbidden as result. The patch is solves this issue.
=> apiKey support for yandex is implemented

package.json
Currently the OpenDataFrance always requests 20 records at a time via `limit`. Turns out we don't need to set a `limit` at all - the API defaults to 5 without the parameter being set - and with this addition we can pass our own custom limit in.
=> Allow passing of limit parameter to opendatafrance

index.js, lib/geocoder/opencagegeocoder.js
In this pull request, I added language param to opencage API as described in [opencage api](https://opencagedata.com/api#request) so it will attempt to return the response in the local language (ie. value we passed to language parameter during instantiating the geocoder object).
before making this PR I looked some part of the [code](https://github.com/nchaulet/node-geocoder/blob/51575ca573440f422944b8f0b307db749555be59/lib/geocoder/opencagegeocoder.js#L155), it looks like implement the language parameter but I don't know how to use it, so please review this PR. thanks
=> add opencage language feature

.jshintrc, lib/geocoder/heregeocoder.js, lib/httpadapter/fetchadapter.js
- Improves the `fetchadapter` to handle non-JSON responses (like for TomTom APIs)
- Fixes error handling on Here geocoder, to parse ApplicationError type responses
=> Improving error handling

README.md, lib/geocoder/mapboxgeocoder.js, lib/geocoderfactory.js, test/geocoder/mapboxgeocoder.test.js
Implements a mapbox geocoder with forward and reverse search. 
See https://docs.mapbox.com/api/search/geocoding/
Assigned feature-request #287
=> feat: mapbox geocoder

integration_test/geocoder/tomtomgeocoder.test.js, lib/geocoder/abstractgeocoder.js, lib/geocoder/tomtomgeocoder.js
Standardize batch output:
```json
[
{
"error": null,
"value": [
{
// ... geocoding intem
}
]
},
{
"error": "...",
"value": []
}
]
```
Note: I would say that `values` it's more semantically accurate but since it was already `value` let's keep that way for compatibility. Sorry I had introduced this bug 😞
=> Standardize batch output

lib/geocoder/tomtomgeocoder.js
- If `country` was passed as an option when instantiating the geocoder, it will be propagated to the TomTom API as the `countrySet` argument.
- The TomTom API `countrySet` parameter really accepts a comma-separated list of Alpha2 coudes (`ES,AU,US`), but for simplicity and to avoid maintaining redundant validations (the TomTom API will already be validating the format of this) we decided just to propagate the value as it is received.
=> Propagate country param to TomTom geocoder

lib/geocoder/locationiqgeocoder.js, test/geocoder/locationiqgeocoder.test.js
Support to endpoint http://locationiq.org & http://locationiq.com has been deprecated. Changed URLs & tests to reflect the documented endpoints
=> Changes to LocationIQ API URLs

lib/geocoder/heregeocoder.js
Passing "united states" as a attribute for the geocoder, like
const data: any = await geocoder.geocode(location);
but getting Error:
return target.apply(this, arguments);
^
TypeError: Cannot read properties of undefined (reading 'View')
at /home/aximsoft/Project/secuvy/api/command-center/node_modules/node-geocoder/lib/geocoder/heregeocoder.js:81:36
at tryCatcher (/home/aximsoft/Project/secuvy/api/command-center/node_modules/bluebird/js/release/util.js:16:23)
at Promise.successAdapter [as _fulfillmentHandler0] (/home/aximsoft/Project/secuvy/api/command-center/node_modules/bluebird/js/release/nodeify.js:23:30)
at Promise._settlePromise (/home/aximsoft/Project/secuvy/api/command-center/node_modules/bluebird/js/release/promise.js:601:21)
at Promise._settlePromise0 …
=> Handling undefined values

lib/geocoder/openstreetmapgeocoder.js
Fixes https://github.com/nchaulet/node-geocoder/issues/350.
I would really appreciate if this could be merged in the near future, as it's affecting the uptime of my app.
Usage (the try/catch doesn't help):
```
await geocoder
.geocode(privateListingRes.address)
.then((entries) => {
const entry = entries[0];
if (entry?.latitude && entry.longitude) {
latitude = entry.latitude;
longitude = entry.longitude;
}
})
.catch(() => undefined);
```
Error: 
```
TypeError: Cannot read properties of undefined (reading 'country_code')
at OpenStreetMapGeocoder._formatResult (/home/ec2-user/superset/node_modules/.pnpm/node-geocoder@4.2.0/node_modules/node-geocoder/lib/geocoder/openstreetmapgeocoder.js:71:38)
at /home/ec2-user/superset/node_modules/.pnpm/node-geocoder@4.2.0/node_modules/node-geocoder/lib/geoc …
```
=> [Fix] Cannot read properties of undefined (reading 'country_code')

lib/httpadapter/fetchadapter.js
Fix "body used already for" error message as json and text is called. Should fix https://github.com/nchaulet/node-geocoder/issues/340
=> fix: body used already error fix #340

lib/geocoder/locationiqgeocoder.js
⚡️ Enhance locationiq geocoder:
- add formattedAddress
- add county
- unify country name
closes https://github.com/nchaulet/node-geocoder/issues/336
closes https://github.com/nchaulet/node-geocoder/issues/337
=> ⚡️ Enhance locationiq - formattedAddress, county, unify country name
