nchaulet/node-geocoder

package.json
So the require-statement in README really works :)
=> Fixed main entry in package.json

lib/geocoder/nominatimmapquestgeocoder.js, lib/geocoder/openstreetmapgeocoder.js, test/geocoder/nominatimmapquestgeocoder.js, test/geocoder/openstreetmapgeocoder.js
Replaced mocked results with real service responses, fixed code to adhere to the tests again.
Had to replace "Champs-Élysées" by some request returning proper street numbers...
=> Fixed nomination based geocoders

lib/geocoder/agolgeocoder.js, lib/geocoder/datasciencetoolkitgeocoder.js, lib/geocoder/freegeoipgeocoder.js, lib/geocoder/googlegeocoder.js, lib/geocoder/mapquestgeocoder.js, lib/geocoder/nominatimmapquestgeocoder.js, lib/geocoder/opencagegeocoder.js, lib/geocoder/openmapquestgeocoder.js, lib/geocoder/openstreetmapgeocoder.js, lib/geocoder/smartystreetsgeocoder.js, lib/geocoder/tomtomgeocoder.js, test/geocoder/googlegeocoder.js, test/geocoder/opencagegeocoder.js, test/geocoder/openstreetmapgeocoder.js
=> Returning raw result as property of data array

lib/geocoder/abstractgeocoder.js, lib/geocoder/agolgeocoder.js, lib/geocoder/datasciencetoolkitgeocoder.js, lib/geocoder/freegeoipgeocoder.js, lib/geocoder/googlegeocoder.js, lib/geocoder/mapquestgeocoder.js, lib/geocoder/nominatimmapquestgeocoder.js, lib/geocoder/opencagegeocoder.js, lib/geocoder/openmapquestgeocoder.js, lib/geocoder/openstreetmapgeocoder.js, lib/geocoder/smartystreetsgeocoder.js, lib/geocoder/tomtomgeocoder.js, test/geocoder/nominatimmapquestgeocoder.js, test/geocoder/openstreetmapgeocoder.js
Is based on fixes from PR #83, so it includes the commit from #83
=> Refactored nominatim geocoders

lib/geocoder/nominatimmapquestgeocoder.js
Somehow, this got lost when merging PR #84, so I deleted the duplicated code.
=> Removed duplicated code from NominatimMapquestGeocoder

CHANGELOG.md, README.md, lib/geocoder/openstreetmapgeocoder.js, test/geocoder/openstreetmapgeocoder.js
Now you can specify the additional parameters (zoom, limit, ...) in your request.
Based on PR #85 , so it includes #85, #84 and #83
=> Extended nominatim requests

lib/geocoder/openstreetmapgeocoder.js
Adding village and hamlet as small towns.
=> added village and hamlet as city.

lib/geocoder/googlegeocoder.js, lib/geocoderfactory.js, test/geocoder/googlegeocoder.js
Adds options to include place_id and/or formatted_address when using google as the geocoder
=> Add support for place_id and formatted_address

lib/geocoder/googlegeocoder.js, test/geocoder/googlegeocoder.js
This adds the establishment, premise, subpremise, and neighborhood properties from the Google Geocoding API. https://developers.google.com/maps/documentation/geocoding/#Types
=> Add establishment

lib/geocoder/smartystreetsgeocoder.js
=> fix smarty streets geocoder

lib/geocoder/openstreetmapgeocoder.js
=> Fix throw error

lib/geocoder/openmapquestgeocoder.js
=> handled bad response from openmapquest

lib/formatter/stringformatter.js, lib/geocoder/abstractgeocoder.js, lib/geocoder/geocodiogeocoder.js, lib/geocoder/googlegeocoder.js, lib/geocoder/mapquestgeocoder.js, lib/geocoder/opencagegeocoder.js, lib/geocoder/openmapquestgeocoder.js, lib/geocoder/tomtomgeocoder.js
=> fix typo undefinded 

README.md, lib/geocoder/heregeocoder.js, lib/geocoderfactory.js, test/geocoder/heregeocoder.js, test/geocoderfactory.js
This is a pull request with implementation and tests for the [Here Geocoder](https://developer.here.com/api-explorer/rest/geocoder), related to issue #118.
It's inspired by the implementation of GoogleGeocoder. Both `npm test` and `jshint lib test` should work fine. If you have any questions, please just ask me.
=> Implementing Here Geocoder with tests

lib/geocoder/googlegeocoder.js, lib/geocoderfactory.js, test/geocoder/googlegeocoder.js, test/geocoderfactory.js
Hello
I didn't realise that I had to modify the geocoderfactory to allow me to pass the option through to the googlecoder.
This has now been fixed, I have also made some slight logic tweaks and added an additional test.
Sorry
Lee
=> Lee Crowe - Google geocoding exclude partial matches fixes

README.md, lib/httpadapter/httpadapter.js, lib/httpadapter/httpsadapter.js, test/httpadapter/httpadapter.js
As e.g. required by open streetmap
=> Extended default http adapter to explicitely set http-get options

lib/geocoder/googlegeocoder.js
Before there was no way to resolve place by google place id.
=> Added support of to resolve place by Google Maps PlaceId

lib/geocoder/agolgeocoder.js
=> fix agol geocoder

README.md, lib/geocoder/mapquestgeocoder.js
=> Allow to use search object with mapquest geocoder

lib/geocoder/opencagegeocoder.js
Fix for: https://github.com/nchaulet/node-geocoder/issues/145
=> opencagegeo should use callback on err

.gitignore, lib/geocoder/opencagegeocoder.js, test/geocoder/opencagegeocoder.js
Fixes: https://github.com/nchaulet/node-geocoder/issues/131
=> Add confidence in km to opencage

lib/geocoder/googlegeocoder.js, lib/geocoderfactory.js
Added support of channels to Google Geocoding
More details: https://developers.google.com/maps/premium/reports/usage-reports#channels
=> Google geocoding: Added supporting of channels

lib/geocoder/googlegeocoder.js
=> Escape substitute string

lib/geocoder/googlegeocoder.js, test/geocoder/googlegeocoder.js
Geocode url example: https://maps.googleapis.com/maps/api/geocode/json?address=Rua%20Marilia%20116%20Praia%20Grande
=> fix(*): neighboorhood is now retrivied.

lib/geocoder/opendatafrancegeocoder.js, test/geocoder/opendatafrancegeocoder.js
I've added some options to OpenData France Geocoder
You can find more information here : http://adresse.data.gouv.fr/api/
=> Added some options to OpenData France Geocoder

lib/geocoder/agolgeocoder.js
Combine three identical if statements
=> Clean up extra if statements

lib/geocoder/opendatafrancegeocoder.js, test/geocoder/opendatafrancegeocoder.js
Sorry for this third PR but i just realize that the API return differents type of objects.
This commit format results by type
Test included
=> Format results by type for opendatafrance geocoder

lib/geocoder.js, package.json, test/geocoder.js
=> Remove Q and use bluebird instead

lib/geocoder/mapquestgeocoder.js
=> Fix mapquest geocoder with no results

lib/geocoderfactory.js, test/geocoderfactory.js
=> Simplify geocoder factory

lib/geocoder.js
=> Global implementation of minConfidence

lib/geocoder.js, lib/geocoder/abstractgeocoder.js
=> Add provider to geocoder results

.travis.yml, lib/geocoder.js, lib/geocoderfactory.js, package.json
=> Remove all dynamics require

test/geocoder/heregeocoder.js
=> Update Test heregeocoder,js

lib/geocoder/googlegeocoder.js, test/geocoder/googlegeocoder.js
=> Optional params support google reverse geocoding

lib/geocoder/locationiqgeocoder.js
As I have been using this library, I noticed responseData.map errors out on empty arrays returned by locationiq. This code is to handle that error.
=> handle empty array being returned by locationiq

lib/geocoder/openstreetmapgeocoder.js, test/geocoder/nominatimmapquestgeocoder.js, test/geocoder/openstreetmapgeocoder.js
[issue 219](https://github.com/nchaulet/node-geocoder/issues/219)
=> Add display name to openstreetmap geocoder

README.md, lib/geocoder/virtualearth.js, lib/geocoderfactory.js
This adds virtualearth (aka Microsoft Bing Maps) as a geocoder.
=> add virtualearth (aka Bing Maps) support

README.md, lib/geocoder/openstreetmapgeocoder.js, lib/geocoderfactory.js, lib/httpadapter/httpadapter.js
Supports custom servers support for osm nominatim. Closes #230 
Passing `npm test` and `npm run lint`
=> support custom server for osm nominatim

lib/geocoder/googlegeocoder.js, test/geocoder/googlegeocoder.test.js
Issue described here:
https://github.com/nchaulet/node-geocoder/issues/238
=> Fix GoogleGeocoder ignoring post code when country is null

lib/geocoder/virtualearth.js
Add support for Bing reverse geocoding and add formattedAddress to the results.
=> Bing Reverse Geocoding

README.md, test/formatter/stringformatter.test.js
Added the city pattern "%c" to the README and added a usage of it in the string formatter test.
=> Document/test city option in formatterPattern

package.json
request, request-promise, bluebird bump
=> request, request-promise, bluebird bump

README.md
=> Fix nominatim documentation link

lib/geocoder/yandexgeocoder.js
See https://github.com/nchaulet/node-geocoder/issues/288
=> fix(yandex): fix wrong parameter usage #288

lib/geocoder/geocodiogeocoder.js
Added formattedAddress and fixed country for geocodio. Verified these two fields work just fine. All tests passed.
=> Fixed GeoCodio Object

lib/geocoder/heregeocoder.js, lib/geocoderfactory.js, lib/httpadapter/fetchadapter.js
- Implements `_batchGeocode` on `HereGeocoder` to use the [Here Batch API](https://developer.here.com/documentation/batch-geocoder/dev_guide/topics/introduction.html)
=> Here batchGeocoding using the Here Batch API

lib/geocoder/heregeocoder.js, lib/geocoder/mapboxgeocoder.js
Remove appId and appCode from here geocoder
=> Remove deprecated option from here geocoder

README.md, lib/geocoder/aplacegeocoder.js, lib/geocoderfactory.js, test/geocoder/aplacegeocoder.test.js
Adding APlace.io Geocoding service. Supports geocoding and reverse.
=> adding new geocoder APlace.io
